# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.8

before_install:
  - mkdir ~/.aws
  - echo -e "machine github.com\n login $CI_USER_TOKEN" > ~/.netrc
  - echo -e "[default]" > ~/.aws/config
  - echo -e "region=us-east-1" >> ~/.aws/config
  - echo -e "[default]" > ~/.aws/credentials
  - echo -e "aws_access_key_d=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
  - echo -e "aws_secret_access_key=AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

install:
  - pipenv install --dev --ignore-pipfile --deploy
  - pipenv install wheel
before_script: # code coverage tool
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
   - ./cc-test-reporter before-build
script:
  - make && pytest --cov-report xml --cov-report term
  - sam validate -t final_project_search_lambda/template.yaml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  skip_cleanup: true
  on:
    branch:
      - main
      - master
      - dev
  provider: script
  # Before running, get the data from s3 using the secret

  # credentials entered at https://travis-ci.com/csci-e-29/YOUR_PSET_REPO_NAME/settings
  # DO NOT commit these variables to git.
  script: make && pipenv run python -m final_project_file_load &&
        sam build --template final_project_search_lambda/template.yaml --build-dir final_project_search_lambda/.aws-sam/build &&
        sam package --template-file final_project_search_lambda/.aws-sam/build/template.yaml --output-template-file final_project_search_lambda/.aws-sam/build/packaged-template.yaml --s3-bucket lambdadeploybucket08may2021 &&
        sam deploy --template-file final_project_search_lambda/.aws-sam/build/packaged-template.yaml --stack-name GetProductV11 --s3-bucket lambdadeploybucket08may2021 --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM